### ISSUE TITLE
Problem with --enable-libsvthevc while compiling ffmpeg

### ISSUE THREAD

**Issue by komar007** [five82/ffmpeg-git#4]
`build-ffmpeg.sh` fails when trying to patch ffmpeg with SVT-HEVC patches:

```
error: can't open patch '/ffmpeg/ffmpeg_sources/SVT-HEVC/ffmpeg_plugin/0001*.patch': No such file or directory
```

It looks like something changed in SVT-HEVC since the scripts were written and this wildcard does not match anything anymore. As a result, ffmpeg's `./configure` fails on `--enable-libsvthevc`. It seems this does not cause the build process to exit with error, so the build continues and the resultant docker image does not contain ffmpeg at all. Also the current build available on dockerhub (`five82/ffmpeg-git:latest`) contains no ffmpeg. It might be affected by this problem.

**Comment by five82** [comment]
Are you using SVT-HEVC? I was considering removing it and SVT-VP9.

**Comment by komar007** [comment]
In fact I'm not using either. I was after SVT-AV1, and it worked fine after removing everything that caused problems.

**Comment by five82** [comment]
Removed libsvthevc in bd5a33574b8ffbab3e7ff8fb75b224c8ecbc1ca0
